services:
  - type: web
    name: construction-backend
    env: python
    plan: starter
    rootDir: backend
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: false
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: JWT_ACCESS_MINUTES
        value: 60
      - key: AUTH_USER_MODEL
        value: users.CustomUser
      - key: CORS_ALLOW_ALL_ORIGINS
        value: 1
